"use client";

import { FormEvent, useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import type { TechnologyContent } from "@/lib/technology-content";

export function AdminTechnologyEditor() {
  const [content, setContent] = useState<TechnologyContent | null>(null);
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/admin/technology").then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setContent(result); }).catch(error => toast.error(error instanceof Error ? error.message : "Технологийн агуулгыг уншиж чадсангүй.")); }, []);
  if (!content) return <div className="admin-card"><p>Уншиж байна...</p></div>;
  function update<K extends keyof TechnologyContent>(field: K, value: TechnologyContent[K]) { setContent(current => current ? { ...current, [field]: value } : current); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { const response = await fetch("/api/admin/technology", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(content) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Хадгалж чадсангүй."); setContent(result); toast.success("Барилгын технологийн мэдээлэл хадгалагдлаа."); } catch (error) { toast.error(error instanceof Error ? error.message : "Хадгалж чадсангүй."); } finally { setBusy(false); } }
  return <form onSubmit={save}>
    <div className="admin-top"><div><h1>Барилгын технологи</h1><small>Технологийн хуудасны бүх текст, давхарга, карт удирдах</small></div><button className="button" disabled={busy}>{busy ? "Хадгалж байна..." : "Хадгалах"}</button></div>
    <section className="admin-card admin-editor"><div className="admin-editor-head"><div><span>ХУУДАСНЫ ТОЛГОЙ</span><h2>Үндсэн мэдээлэл</h2></div></div><div className="field-grid"><div className="field"><label>Жижиг гарчиг *</label><input required value={content.eyebrow} onChange={event => update("eyebrow", event.target.value)} /></div><div className="field"><label>Үндсэн гарчиг *</label><input required value={content.title} onChange={event => update("title", event.target.value)} /></div><div className="field full"><label>Тайлбар *</label><textarea required rows={4} value={content.copy} onChange={event => update("copy", event.target.value)} /></div></div></section>
    <section className="admin-card admin-editor"><div className="admin-editor-head"><div><span>ХАНЫН БҮТЭЦ</span><h2>Давхаргын мэдээлэл</h2></div></div><div className="field-grid"><div className="field"><label>Жижиг гарчиг *</label><input required value={content.wallEyebrow} onChange={event => update("wallEyebrow", event.target.value)} /></div><div className="field"><label>Үндсэн гарчиг *</label><input required value={content.wallTitle} onChange={event => update("wallTitle", event.target.value)} /></div><div className="field full"><label>Тайлбар *</label><textarea required rows={3} value={content.wallCopy} onChange={event => update("wallCopy", event.target.value)} /></div><div className="field full"><label>Давхаргууд <small className="field-help">Мөр бүрт нэг давхарга</small></label><textarea required rows={7} value={content.layers.join("\n")} onChange={event => update("layers", event.target.value.split("\n"))} /></div></div></section>
    <section className="admin-card admin-editor technology-card-editor"><div className="admin-editor-head"><div><span>ТЕХНОЛОГИЙН ХЭСГҮҮД</span><h2>{content.cards.length} карт</h2></div><button type="button" className="button secondary" onClick={() => update("cards", [...content.cards, { title: "Шинэ хэсэг", description: "Тайлбар оруулна уу." }])}><Plus size={16} /> Нэмэх</button></div>{content.cards.map((card, index) => <div className="admin-content-row" key={`${card.title}-${index}`}><strong>{String(index + 1).padStart(2, "0")}</strong><div className="field"><label>Гарчиг</label><input value={card.title} onChange={event => update("cards", content.cards.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} /></div><div className="field"><label>Тайлбар</label><textarea rows={2} value={card.description} onChange={event => update("cards", content.cards.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item))} /></div><button type="button" className="admin-action danger" title="Устгах" aria-label="Карт устгах" onClick={() => update("cards", content.cards.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={16} /></button></div>)}</section>
  </form>;
}
