import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Download } from "lucide-react";
import { notFound } from "next/navigation";
import { models } from "@/lib/data";

export function generateStaticParams(){return models.map(m=>({slug:m.slug}))}
export default async function HouseDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const m=models.find(x=>x.slug===slug);if(!m)notFound();return <>
  <div className="detail-hero" style={{backgroundImage:`linear-gradient(0deg,rgba(11,20,25,.25),transparent),url(${m.image})`}}/>
  <section className="section" style={{paddingTop:0}}><div className="container"><div className="detail-title"><div className="eyebrow">{m.category}</div><h1>{m.name}</h1><p className="section-copy">{m.description}</p><div className="stats"><div className="stat"><span>НИЙТ ТАЛБАЙ</span><strong>{m.area}</strong></div><div className="stat"><span>ХЭМЖЭЭ</span><strong>{m.dimensions}</strong></div><div className="stat"><span>ДАВХАР</span><strong>{m.floors}</strong></div><div className="stat"><span>УНТЛАГЫН ӨРӨӨ</span><strong>{m.bedrooms}</strong></div><div className="stat"><span>АРИУН ЦЭВРИЙН ӨРӨӨ</span><strong>{m.bathrooms}</strong></div></div><div className="hero-actions"><Link className="button" href={`/quote?model=${m.slug}`}>Үнийн санал авах <ArrowRight size={17}/></Link><button className="button dark"><Download size={17}/> PDF танилцуулга</button></div></div>
  <div className="content-grid section"><div className="prose"><div className="eyebrow">Загварын тухай</div><h2>Монгол ахуйд нийцсэн төлөвлөлт</h2><p>Өдрийн гэрлийг дээд зэргээр ашиглах нийтийн хэсэг, хувийн орон зайн тодорхой бүсчлэл, хадгалалтын цэгцтэй шийдэлтэй. Байршил, газрын хэлбэр, салхины зонхилох чиглэлд үндэслэн цонх, террас, орцын чиглэлийг тохируулна.</p><Image src="/images/interior.png" alt="Хаусын интерьер" width={1000} height={667}/><h2>Материал ба гүйцэтгэл</h2><p>Каркас, дулаалга, уур болон салхины хамгаалалт, фасад, инженерийн системийн үзүүлэлтүүдийг ажлын зураг болон баталгаажсан төсөвт тусгана. Бодит техникийн утга, үйлдвэрлэгчийн мэдээллийг төслийн нөхцөл тодорхой болсны дараа баталгаажуулна.</p><h2>Үнийн мэдээлэл</h2><p><strong>Төслийн нөхцөлөөс хамаарч үнэ тооцно.</strong></p></div><aside><div className="aside-box"><h3>Багцад багтах ажил</h3><ul><li>Архитектур төлөвлөлт</li><li>Хийцийн ажлын зураг</li><li>Материалын тооцоо</li><li>Барилга угсралтын ажил</li><li>Үе шатны чанарын хяналт</li></ul><Link className="button" href={`/quote?model=${m.slug}`}>Хүсэлт илгээх</Link></div></aside></div>
  </div></section></>}
