import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { z } from "zod";
import { appendFile, mkdir } from "node:fs/promises";
import path from "node:path";

const schema=z.object({name:z.string().min(2).max(100),phone:z.string().min(8).max(30),email:z.string().email().optional().or(z.literal('')),location:z.string().min(2).max(200),consent:z.union([z.literal('true'),z.literal('on')]),model:z.string().optional(),area:z.string().optional(),floors:z.string().optional(),rooms:z.string().optional(),bedrooms:z.string().optional(),landReady:z.string().optional(),landSize:z.string().optional(),electricity:z.string().optional(),water:z.string().optional(),landNote:z.string().max(2000).optional(),schedule:z.string().optional(),budget:z.string().optional(),service:z.string().optional(),requirements:z.string().max(4000).optional(),contactMethod:z.string().optional()});
const recent=new Map<string,number>();
export async function POST(request:NextRequest){const ip=request.headers.get('x-forwarded-for')?.split(',')[0]||'local';const now=Date.now();if(now-(recent.get(ip)||0)<15000)return NextResponse.json({error:'Түр хүлээгээд дахин оролдоно уу.'},{status:429});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:'Хүсэлтийн формат буруу.'},{status:400})}const parsed=schema.safeParse(body);if(!parsed.success)return NextResponse.json({error:'Заавал бөглөх мэдээллийг шалгана уу.'},{status:400});recent.set(ip,now);const enquiryNumber=`NH-${new Date().getFullYear()}-${String(now).slice(-6)}`;const record={enquiry_number:enquiryNumber,customer_name:parsed.data.name,phone:parsed.data.phone,email:parsed.data.email||null,location:parsed.data.location,interested_model:parsed.data.model||null,budget:parsed.data.budget||null,status:'Шинэ',source_page:'/quote',consent_at:new Date().toISOString(),form_data:parsed.data};const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(url&&key){const db=createClient(url,key,{auth:{persistSession:false}});const {error}=await db.from('quotation_enquiries').insert(record);if(error)return NextResponse.json({error:'Хүсэлтийг хадгалж чадсангүй.'},{status:500})}else if(process.env.NODE_ENV!=='production'){const dir=path.join(process.cwd(),'data');await mkdir(dir,{recursive:true});await appendFile(path.join(dir,'enquiries.ndjson'),JSON.stringify(record)+'\n','utf8')}else{return NextResponse.json({error:'Мэдээллийн сангийн тохиргоо дутуу байна.'},{status:503})}return NextResponse.json({ok:true,enquiryNumber},{status:201})}
